# Generated by Django 5.1.2 on 2025-10-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_campus_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
