# Generated by Django 5.1.2 on 2025-10-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_building_latitude_alter_building_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='building',
            name='type',
        ),
    ]
