# Generated by Django 5.1.2 on 2025-10-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_campus_address_alter_campus_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
