# Generated by Django 5.1.2 on 2025-10-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
