# Generated by Django 5.1.2 on 2025-10-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='area',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='description',
        ),
    ]
